// File generated by Antigravity Assistant for TopSavdo.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Mb-f29-2zorl4D5QMotHnuwiUBnRazo',
    appId: '1:913099050488:web:e095ae35bee6375520da0d',
    messagingSenderId: '913099050488',
    projectId: 'topsavdo-2bc8a',
    authDomain: 'topsavdo-2bc8a.firebaseapp.com',
    storageBucket: 'topsavdo-2bc8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkPkyzyFEQGp_j_-QlUP62O4DBpAJHRuI',
    appId: '1:913099050488:android:915660e6a46ca92520da0d',
    messagingSenderId: '913099050488',
    projectId: 'topsavdo-2bc8a',
    storageBucket: 'topsavdo-2bc8a.firebasestorage.app',
  );
}
